# Generated by Django 4.2.3 on 2023-08-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
